CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
brute_force: brute_force.cpp
	g++ $(CXXFLAGS) brute_force.cpp -o brute_force
kmp: kmp.cpp
	g++ $(CXXFLAGS) kmp.cpp -o kmp