CXXFLAGS=-ggdb -std=c++11 -Wpedantic -Wall -Wextra -Werror -Wzero-as-null-pointer-constant
hw2-1: hw2-1.cpp
	g++ hw2-1.cpp -o hw2-1
hw2-2: hw2-2.cpp
	g++ hw2-2.cpp -o hw2-2
hw2-3: hw2-3.cpp
	g++ hw2-3.cpp -o hw2-3
hw2-4: hw2-4.cpp
	g++ hw2-4.cpp -o hw2-4